name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./instrumentation-api/build/reports/jacoco/test/jacocoTestReport.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
